PANDARIA: mirror nginx 1.23.3
cnrancher/image-mirror pull request #9
Opened 2023-03-16 09:25 UTC by GGGitBoy

#### Pull Request Checklist ####

- [x] Change does not remove any existing Images or Tags in the images-list file
- [x] Change does not remove / overwrite exiting Images or Tags in Rancher DockerHub
- [x] If updating an existing entry, verify the `SOURCE` is still accurate and upstream hasn't been migrated to a new regitry or repo (if they've migrated, a new repo request to EIO is needed to comply with the `SOURCE DESTINATION TAG` pattern)
- [x] New entries are in format `SOURCE DESTINATION TAG`
- [x] New entries are added to the correct section of the list (sorted lexicographically)
- [x] New entries have a repo created in Rancher Dockerhub (where the image will be mirrored to)
- [x] Changes to scripting or CI config have been tested to the best of your ability

#### Types of Change ####
New image

#### Linked Issues ####
https://github.com/cnrancher/pandaria-images-scanning/issues/68

#### Additional Notes ####

最近发布的 nginx 1.23.3 没有 HIGH,CRITICAL 级别 cve，社区版的 mirror list 还没同步
```
trivy image --no-progress --ignore-unfixed --severity HIGH,CRITICAL --security-checks vuln --exit-code 1 library/nginx:1.23.3
2023-03-16T17:16:11.391+0800	INFO	Vulnerability scanning is enabled
2023-03-16T17:16:17.334+0800	INFO	Detected OS: debian
2023-03-16T17:16:17.334+0800	INFO	Detecting Debian vulnerabilities...
2023-03-16T17:16:17.395+0800	INFO	Number of language-specific files: 0

library/nginx:1.23.3 (debian 11.6)

Total: 0 (HIGH: 0, CRITICAL: 0)
```

#### Final Checks after the PR is merged ####
- [ ] Confirm that you can pull the new images and tags from DockerHub

2023-03-16 09:28 UTC, Jason-ZW requested changes
mirror的镜像是否要按照命名规则去定义 mirror-xxx

2023-03-16 09:33 UTC, GGGitBoy commented
已更新

2023-03-16 10:02 UTC, Jason-ZW commented on images-list
> +library/nginx cnrancher/mirrored-library-nginx 1.23.3
library/nginx -> cnrancher/mirrored-library-nginx 1.23.3
nginx -> cnrancher/mirrored-nginx 1.23.3
是否这么改更合理？

2023-03-16 10:05 UTC, GGGitBoy commented on images-list
> +library/nginx cnrancher/mirrored-library-nginx 1.23.3
https://github.com/rancher/image-mirror/blob/master/images-list#L437-L444
<img width="926" alt="截屏2023-03-16 18 03 15" src="https://user-images.githubusercontent.com/51182588/225583322-8fcddefd-7c61-42da-9781-40757d32db51.png">

刚那么改是按着社区版的命名规范

2023-03-17 08:00 UTC, Jason-ZW approved these changes
LGTM

2023-03-17 08:00 UTC, merged